name = "eoh-web"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build"
cwd = "./"

[build.upload]
main = "./functions/_middleware.ts"

[env.production]
name = "eoh-web-production"

[compatibility_flags]
nodejs_compat = true

[env.production.compatibility_flags]
nodejs_compat = true
